const city =
{"location":
    {"name":"Indore - ( OFFLINE )",
    "region":"Madhya Pradesh",
    "country":"India",
    "lat":22.76,
    "lon":75.88,
    "tz_id":"Asia/Kolkata",
    "localtime_epoch":1609325838,
    "localtime":"2020-12-30 16:27"
    },
"current":
    {"last_updated_epoch":1609325109,
    "last_updated":"2020-12-30 16:15",
    "temp_c":18.0,"temp_f":64.4,"is_day":1,
    "condition":
            {"text":"Mist",
            "icon":"//cdn.weatherapi.com/weather/64x64/day/143.png",
            "code":1030 
            },
    "wind_mph":6.9,
    "wind_kph":11.2,
    "wind_degree":80,
    "wind_dir":"E",
    "pressure_mb":1015.0,
    "pressure_in":30.4,
    "precip_mm":0.0,
    "precip_in":0.0,
    "humidity":49,
    "cloud":25,
    "feelslike_c":18.0,
    "feelslike_f":64.4,
    "vis_km":3.0,
    "vis_miles":1.0,
    "uv":6.0,
    "gust_mph":10.1,
    "gust_kph":16.2
    } , 
    forecast : {
        "forecastday": [
            {
                "date": "2020-12-30",
                "date_epoch": 1609286400,
                "day": {
                    "maxtemp_c": 29.1,
                    "maxtemp_f": 84.4,
                    "mintemp_c": 18.3,
                    "mintemp_f": 64.9,
                    "avgtemp_c": 23.3,
                    "avgtemp_f": 74.0,
                    "maxwind_mph": 10.1,
                    "maxwind_kph": 16.2,
                    "totalprecip_mm": 0.0,
                    "totalprecip_in": 0.0,
                    "avgvis_km": 10.0,
                    "avgvis_miles": 6.0,
                    "avghumidity": 75.0,
                    "daily_will_it_rain": 0,
                    "daily_chance_of_rain": "0",
                    "daily_will_it_snow": 0,
                    "daily_chance_of_snow": "0",
                    "condition": {
                        "text": "Partly cloudy",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                        "code": 1003
                    },
                    "uv": 7.0
                },
                "astro": {
                    "sunrise": "06:36 AM",
                    "sunset": "05:36 PM",
                    "moonrise": "06:15 PM",
                    "moonset": "07:03 AM",
                    "moon_phase": "Waning Gibbous",
                    "moon_illumination": "97"
                },
                "hour": [
                    {
                        "time_epoch": 1609308000,
                        "time": "2020-12-30 00:00",
                        "temp_c": 21.1,
                        "temp_f": 70.0,
                        "is_day": 0,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            "code": 1003
                        },
                        "wind_mph": 9.6,
                        "wind_kph": 15.5,
                        "wind_degree": 105,
                        "wind_dir": "ESE",
                        "pressure_mb": 1016.0,
                        "pressure_in": 30.5,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 80,
                        "cloud": 16,
                        "feelslike_c": 21.1,
                        "feelslike_f": 70.0,
                        "windchill_c": 21.1,
                        "windchill_f": 70.0,
                        "heatindex_c": 22.1,
                        "heatindex_f": 71.8,
                        "dewpoint_c": 17.5,
                        "dewpoint_f": 63.5,
                        "will_it_rain": 0,
                        "chance_of_rain": "0",
                        "will_it_snow": 0,
                        "chance_of_snow": "0",
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 16.1,
                        "gust_kph": 25.9
                    },
                    {
                        "time_epoch": 1609311600,
                        "time": "2020-12-30 01:00",
                        "temp_c": 21.0,
                        "temp_f": 69.8,
                        "is_day": 0,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            "code": 1003
                        },
                        "wind_mph": 10.1,
                        "wind_kph": 16.2,
                        "wind_degree": 113,
                        "wind_dir": "ESE",
                        "pressure_mb": 1015.0,
                        "pressure_in": 30.5,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 81,
                        "cloud": 19,
                        "feelslike_c": 21.0,
                        "feelslike_f": 69.8,
                        "windchill_c": 21.0,
                        "windchill_f": 69.8,
                        "heatindex_c": 21.0,
                        "heatindex_f": 69.8,
                        "dewpoint_c": 17.6,
                        "dewpoint_f": 63.7,
                        "will_it_rain": 0,
                        "chance_of_rain": "0",
                        "will_it_snow": 0,
                        "chance_of_snow": "0",
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 16.3,
                        "gust_kph": 26.3
                    },
                    {
                        "time_epoch": 1609315200,
                        "time": "2020-12-30 02:00",
                        "temp_c": 20.4,
                        "temp_f": 68.7,
                        "is_day": 0,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            "code": 1003
                        },
                        "wind_mph": 9.6,
                        "wind_kph": 15.5,
                        "wind_degree": 112,
                        "wind_dir": "ESE",
                        "pressure_mb": 1015.0,
                        "pressure_in": 30.4,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 84,
                        "cloud": 15,
                        "feelslike_c": 20.4,
                        "feelslike_f": 68.7,
                        "windchill_c": 20.4,
                        "windchill_f": 68.7,
                        "heatindex_c": 20.4,
                        "heatindex_f": 68.7,
                        "dewpoint_c": 17.5,
                        "dewpoint_f": 63.5,
                        "will_it_rain": 0,
                        "chance_of_rain": "0",
                        "will_it_snow": 0,
                        "chance_of_snow": "0",
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 15.9,
                        "gust_kph": 25.6
                    },
                    {
                        "time_epoch": 1609318800,
                        "time": "2020-12-30 03:00",
                        "temp_c": 19.7,
                        "temp_f": 67.5,
                        "is_day": 0,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            "code": 1003
                        },
                        "wind_mph": 9.2,
                        "wind_kph": 14.8,
                        "wind_degree": 112,
                        "wind_dir": "ESE",
                        "pressure_mb": 1014.0,
                        "pressure_in": 30.4,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 86,
                        "cloud": 10,
                        "feelslike_c": 19.7,
                        "feelslike_f": 67.5,
                        "windchill_c": 19.7,
                        "windchill_f": 67.5,
                        "heatindex_c": 19.7,
                        "heatindex_f": 67.5,
                        "dewpoint_c": 17.4,
                        "dewpoint_f": 63.3,
                        "will_it_rain": 0,
                        "chance_of_rain": "0",
                        "will_it_snow": 0,
                        "chance_of_snow": "0",
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 15.4,
                        "gust_kph": 24.8
                    },
                    {
                        "time_epoch": 1609322400,
                        "time": "2020-12-30 04:00",
                        "temp_c": 19.1,
                        "temp_f": 66.4,
                        "is_day": 0,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            "code": 1003
                        },
                        "wind_mph": 8.7,
                        "wind_kph": 14.0,
                        "wind_degree": 111,
                        "wind_dir": "ESE",
                        "pressure_mb": 1014.0,
                        "pressure_in": 30.4,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 89,
                        "cloud": 6,
                        "feelslike_c": 19.1,
                        "feelslike_f": 66.4,
                        "windchill_c": 19.1,
                        "windchill_f": 66.4,
                        "heatindex_c": 19.1,
                        "heatindex_f": 66.4,
                        "dewpoint_c": 17.3,
                        "dewpoint_f": 63.1,
                        "will_it_rain": 0,
                        "chance_of_rain": "0",
                        "will_it_snow": 0,
                        "chance_of_snow": "0",
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 15.0,
                        "gust_kph": 24.1
                    },
                    {
                        "time_epoch": 1609326000,
                        "time": "2020-12-30 05:00",
                        "temp_c": 18.8,
                        "temp_f": 65.8,
                        "is_day": 0,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            "code": 1003
                        },
                        "wind_mph": 8.9,
                        "wind_kph": 14.4,
                        "wind_degree": 112,
                        "wind_dir": "ESE",
                        "pressure_mb": 1014.0,
                        "pressure_in": 30.4,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 90,
                        "cloud": 10,
                        "feelslike_c": 18.8,
                        "feelslike_f": 65.8,
                        "windchill_c": 18.8,
                        "windchill_f": 65.8,
                        "heatindex_c": 18.8,
                        "heatindex_f": 65.8,
                        "dewpoint_c": 17.2,
                        "dewpoint_f": 63.0,
                        "will_it_rain": 0,
                        "chance_of_rain": "0",
                        "will_it_snow": 0,
                        "chance_of_snow": "0",
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 15.2,
                        "gust_kph": 24.5
                    },
                    {
                        "time_epoch": 1609329600,
                        "time": "2020-12-30 06:00",
                        "temp_c": 18.6,
                        "temp_f": 65.5,
                        "is_day": 0,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            "code": 1003
                        },
                        "wind_mph": 9.2,
                        "wind_kph": 14.8,
                        "wind_degree": 114,
                        "wind_dir": "ESE",
                        "pressure_mb": 1014.0,
                        "pressure_in": 30.4,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 91,
                        "cloud": 15,
                        "feelslike_c": 18.6,
                        "feelslike_f": 65.5,
                        "windchill_c": 18.6,
                        "windchill_f": 65.5,
                        "heatindex_c": 18.6,
                        "heatindex_f": 65.5,
                        "dewpoint_c": 17.2,
                        "dewpoint_f": 63.0,
                        "will_it_rain": 0,
                        "chance_of_rain": "0",
                        "will_it_snow": 0,
                        "chance_of_snow": "0",
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 15.4,
                        "gust_kph": 24.8
                    },
                    {
                        "time_epoch": 1609333200,
                        "time": "2020-12-30 07:00",
                        "temp_c": 18.3,
                        "temp_f": 64.9,
                        "is_day": 1,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            "code": 1003
                        },
                        "wind_mph": 9.4,
                        "wind_kph": 15.1,
                        "wind_degree": 115,
                        "wind_dir": "ESE",
                        "pressure_mb": 1014.0,
                        "pressure_in": 30.4,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 93,
                        "cloud": 20,
                        "feelslike_c": 18.3,
                        "feelslike_f": 64.9,
                        "windchill_c": 18.3,
                        "windchill_f": 64.9,
                        "heatindex_c": 18.3,
                        "heatindex_f": 64.9,
                        "dewpoint_c": 17.1,
                        "dewpoint_f": 62.8,
                        "will_it_rain": 0,
                        "chance_of_rain": "0",
                        "will_it_snow": 0,
                        "chance_of_snow": "0",
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 15.7,
                        "gust_kph": 25.2
                    },
                    {
                        "time_epoch": 1609336800,
                        "time": "2020-12-30 08:00",
                        "temp_c": 19.5,
                        "temp_f": 67.1,
                        "is_day": 1,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            "code": 1003
                        },
                        "wind_mph": 9.4,
                        "wind_kph": 15.1,
                        "wind_degree": 116,
                        "wind_dir": "ESE",
                        "pressure_mb": 1014.0,
                        "pressure_in": 30.4,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 87,
                        "cloud": 14,
                        "feelslike_c": 19.5,
                        "feelslike_f": 67.1,
                        "windchill_c": 19.5,
                        "windchill_f": 67.1,
                        "heatindex_c": 20.4,
                        "heatindex_f": 68.7,
                        "dewpoint_c": 17.3,
                        "dewpoint_f": 63.1,
                        "will_it_rain": 0,
                        "chance_of_rain": "0",
                        "will_it_snow": 0,
                        "chance_of_snow": "0",
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 14.5,
                        "gust_kph": 23.4
                    },
                    {
                        "time_epoch": 1609340400,
                        "time": "2020-12-30 09:00",
                        "temp_c": 20.8,
                        "temp_f": 69.4,
                        "is_day": 1,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            "code": 1003
                        },
                        "wind_mph": 9.6,
                        "wind_kph": 15.5,
                        "wind_degree": 117,
                        "wind_dir": "ESE",
                        "pressure_mb": 1014.0,
                        "pressure_in": 30.4,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 82,
                        "cloud": 8,
                        "feelslike_c": 20.8,
                        "feelslike_f": 69.4,
                        "windchill_c": 20.8,
                        "windchill_f": 69.4,
                        "heatindex_c": 22.4,
                        "heatindex_f": 72.3,
                        "dewpoint_c": 17.6,
                        "dewpoint_f": 63.7,
                        "will_it_rain": 0,
                        "chance_of_rain": "0",
                        "will_it_snow": 0,
                        "chance_of_snow": "0",
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 13.6,
                        "gust_kph": 22.0
                    },
                    {
                        "time_epoch": 1609344000,
                        "time": "2020-12-30 10:00",
                        "temp_c": 22.0,
                        "temp_f": 71.6,
                        "is_day": 1,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            "code": 1003
                        },
                        "wind_mph": 9.6,
                        "wind_kph": 15.5,
                        "wind_degree": 118,
                        "wind_dir": "ESE",
                        "pressure_mb": 1014.0,
                        "pressure_in": 30.4,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 77,
                        "cloud": 3,
                        "feelslike_c": 24.5,
                        "feelslike_f": 76.1,
                        "windchill_c": 22.0,
                        "windchill_f": 71.6,
                        "heatindex_c": 24.5,
                        "heatindex_f": 76.1,
                        "dewpoint_c": 17.8,
                        "dewpoint_f": 64.0,
                        "will_it_rain": 0,
                        "chance_of_rain": "0",
                        "will_it_snow": 0,
                        "chance_of_snow": "0",
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 12.5,
                        "gust_kph": 20.2
                    },
                    {
                        "time_epoch": 1609347600,
                        "time": "2020-12-30 11:00",
                        "temp_c": 23.8,
                        "temp_f": 74.8,
                        "is_day": 1,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            "code": 1003
                        },
                        "wind_mph": 8.7,
                        "wind_kph": 14.0,
                        "wind_degree": 122,
                        "wind_dir": "ESE",
                        "pressure_mb": 1014.0,
                        "pressure_in": 30.4,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 70,
                        "cloud": 3,
                        "feelslike_c": 25.9,
                        "feelslike_f": 78.6,
                        "windchill_c": 23.8,
                        "windchill_f": 74.8,
                        "heatindex_c": 25.9,
                        "heatindex_f": 78.6,
                        "dewpoint_c": 17.9,
                        "dewpoint_f": 64.2,
                        "will_it_rain": 0,
                        "chance_of_rain": "0",
                        "will_it_snow": 0,
                        "chance_of_snow": "0",
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 11.4,
                        "gust_kph": 18.4
                    },
                    {
                        "time_epoch": 1609351200,
                        "time": "2020-12-30 12:00",
                        "temp_c": 25.6,
                        "temp_f": 78.1,
                        "is_day": 1,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            "code": 1003
                        },
                        "wind_mph": 8.1,
                        "wind_kph": 13.0,
                        "wind_degree": 125,
                        "wind_dir": "SE",
                        "pressure_mb": 1013.0,
                        "pressure_in": 30.4,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 64,
                        "cloud": 4,
                        "feelslike_c": 27.2,
                        "feelslike_f": 81.0,
                        "windchill_c": 25.6,
                        "windchill_f": 78.1,
                        "heatindex_c": 27.2,
                        "heatindex_f": 81.0,
                        "dewpoint_c": 18.1,
                        "dewpoint_f": 64.6,
                        "will_it_rain": 0,
                        "chance_of_rain": "0",
                        "will_it_snow": 0,
                        "chance_of_snow": "0",
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 10.3,
                        "gust_kph": 16.6
                    },
                    {
                        "time_epoch": 1609354800,
                        "time": "2020-12-30 13:00",
                        "temp_c": 27.4,
                        "temp_f": 81.3,
                        "is_day": 1,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            "code": 1003
                        },
                        "wind_mph": 7.2,
                        "wind_kph": 11.5,
                        "wind_degree": 129,
                        "wind_dir": "SE",
                        "pressure_mb": 1012.0,
                        "pressure_in": 30.4,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 57,
                        "cloud": 4,
                        "feelslike_c": 28.6,
                        "feelslike_f": 83.5,
                        "windchill_c": 27.4,
                        "windchill_f": 81.3,
                        "heatindex_c": 28.6,
                        "heatindex_f": 83.5,
                        "dewpoint_c": 18.2,
                        "dewpoint_f": 64.8,
                        "will_it_rain": 0,
                        "chance_of_rain": "0",
                        "will_it_snow": 0,
                        "chance_of_snow": "0",
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 9.2,
                        "gust_kph": 14.8
                    },
                    {
                        "time_epoch": 1609358400,
                        "time": "2020-12-30 14:00",
                        "temp_c": 28.0,
                        "temp_f": 82.4,
                        "is_day": 1,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            "code": 1003
                        },
                        "wind_mph": 6.5,
                        "wind_kph": 10.4,
                        "wind_degree": 124,
                        "wind_dir": "SE",
                        "pressure_mb": 1011.0,
                        "pressure_in": 30.3,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 57,
                        "cloud": 8,
                        "feelslike_c": 29.4,
                        "feelslike_f": 84.9,
                        "windchill_c": 28.0,
                        "windchill_f": 82.4,
                        "heatindex_c": 29.4,
                        "heatindex_f": 84.9,
                        "dewpoint_c": 18.6,
                        "dewpoint_f": 65.5,
                        "will_it_rain": 0,
                        "chance_of_rain": "0",
                        "will_it_snow": 0,
                        "chance_of_snow": "0",
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 8.7,
                        "gust_kph": 14.0
                    },
                    {
                        "time_epoch": 1609362000,
                        "time": "2020-12-30 15:00",
                        "temp_c": 28.5,
                        "temp_f": 83.3,
                        "is_day": 1,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            "code": 1003
                        },
                        "wind_mph": 5.8,
                        "wind_kph": 9.4,
                        "wind_degree": 119,
                        "wind_dir": "ESE",
                        "pressure_mb": 1009.0,
                        "pressure_in": 30.3,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 56,
                        "cloud": 12,
                        "feelslike_c": 30.1,
                        "feelslike_f": 86.2,
                        "windchill_c": 28.5,
                        "windchill_f": 83.3,
                        "heatindex_c": 30.1,
                        "heatindex_f": 86.2,
                        "dewpoint_c": 19.0,
                        "dewpoint_f": 66.2,
                        "will_it_rain": 0,
                        "chance_of_rain": "0",
                        "will_it_snow": 0,
                        "chance_of_snow": "0",
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 8.5,
                        "gust_kph": 13.7
                    },
                    {
                        "time_epoch": 1609365600,
                        "time": "2020-12-30 16:00",
                        "temp_c": 29.1,
                        "temp_f": 84.4,
                        "is_day": 1,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            "code": 1003
                        },
                        "wind_mph": 5.1,
                        "wind_kph": 8.3,
                        "wind_degree": 114,
                        "wind_dir": "ESE",
                        "pressure_mb": 1008.0,
                        "pressure_in": 30.2,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 56,
                        "cloud": 16,
                        "feelslike_c": 30.9,
                        "feelslike_f": 87.6,
                        "windchill_c": 29.1,
                        "windchill_f": 84.4,
                        "heatindex_c": 30.9,
                        "heatindex_f": 87.6,
                        "dewpoint_c": 19.4,
                        "dewpoint_f": 66.9,
                        "will_it_rain": 0,
                        "chance_of_rain": "0",
                        "will_it_snow": 0,
                        "chance_of_snow": "0",
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 8.1,
                        "gust_kph": 13.0
                    },
                    {
                        "time_epoch": 1609369200,
                        "time": "2020-12-30 17:00",
                        "temp_c": 28.0,
                        "temp_f": 82.4,
                        "is_day": 1,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            "code": 1003
                        },
                        "wind_mph": 5.4,
                        "wind_kph": 8.6,
                        "wind_degree": 109,
                        "wind_dir": "ESE",
                        "pressure_mb": 1008.0,
                        "pressure_in": 30.2,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 60,
                        "cloud": 15,
                        "feelslike_c": 29.7,
                        "feelslike_f": 85.5,
                        "windchill_c": 28.0,
                        "windchill_f": 82.4,
                        "heatindex_c": 29.7,
                        "heatindex_f": 85.5,
                        "dewpoint_c": 19.4,
                        "dewpoint_f": 66.9,
                        "will_it_rain": 0,
                        "chance_of_rain": "0",
                        "will_it_snow": 0,
                        "chance_of_snow": "0",
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 9.6,
                        "gust_kph": 15.5
                    },
                    {
                        "time_epoch": 1609372800,
                        "time": "2020-12-30 18:00",
                        "temp_c": 26.9,
                        "temp_f": 80.4,
                        "is_day": 0,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            "code": 1003
                        },
                        "wind_mph": 5.8,
                        "wind_kph": 9.4,
                        "wind_degree": 103,
                        "wind_dir": "ESE",
                        "pressure_mb": 1008.0,
                        "pressure_in": 30.2,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 64,
                        "cloud": 14,
                        "feelslike_c": 28.6,
                        "feelslike_f": 83.5,
                        "windchill_c": 26.9,
                        "windchill_f": 80.4,
                        "heatindex_c": 28.6,
                        "heatindex_f": 83.5,
                        "dewpoint_c": 19.5,
                        "dewpoint_f": 67.1,
                        "will_it_rain": 0,
                        "chance_of_rain": "0",
                        "will_it_snow": 0,
                        "chance_of_snow": "0",
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 11.2,
                        "gust_kph": 18.0
                    },
                    {
                        "time_epoch": 1609376400,
                        "time": "2020-12-30 19:00",
                        "temp_c": 25.8,
                        "temp_f": 78.4,
                        "is_day": 0,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            "code": 1003
                        },
                        "wind_mph": 6.0,
                        "wind_kph": 9.7,
                        "wind_degree": 98,
                        "wind_dir": "E",
                        "pressure_mb": 1008.0,
                        "pressure_in": 30.2,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 68,
                        "cloud": 13,
                        "feelslike_c": 27.4,
                        "feelslike_f": 81.3,
                        "windchill_c": 25.8,
                        "windchill_f": 78.4,
                        "heatindex_c": 27.4,
                        "heatindex_f": 81.3,
                        "dewpoint_c": 19.5,
                        "dewpoint_f": 67.1,
                        "will_it_rain": 0,
                        "chance_of_rain": "0",
                        "will_it_snow": 0,
                        "chance_of_snow": "0",
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 12.8,
                        "gust_kph": 20.5
                    },
                    {
                        "time_epoch": 1609380000,
                        "time": "2020-12-30 20:00",
                        "temp_c": 25.2,
                        "temp_f": 77.4,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 7.2,
                        "wind_kph": 11.5,
                        "wind_degree": 104,
                        "wind_dir": "ESE",
                        "pressure_mb": 1009.0,
                        "pressure_in": 30.3,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 71,
                        "cloud": 9,
                        "feelslike_c": 26.9,
                        "feelslike_f": 80.4,
                        "windchill_c": 25.2,
                        "windchill_f": 77.4,
                        "heatindex_c": 26.9,
                        "heatindex_f": 80.4,
                        "dewpoint_c": 19.5,
                        "dewpoint_f": 67.1,
                        "will_it_rain": 0,
                        "chance_of_rain": "0",
                        "will_it_snow": 0,
                        "chance_of_snow": "0",
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 14.1,
                        "gust_kph": 22.7
                    },
                    {
                        "time_epoch": 1609383600,
                        "time": "2020-12-30 21:00",
                        "temp_c": 24.5,
                        "temp_f": 76.1,
                        "is_day": 0,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            "code": 1003
                        },
                        "wind_mph": 8.5,
                        "wind_kph": 13.7,
                        "wind_degree": 111,
                        "wind_dir": "ESE",
                        "pressure_mb": 1009.0,
                        "pressure_in": 30.3,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 74,
                        "cloud": 4,
                        "feelslike_c": 26.3,
                        "feelslike_f": 79.3,
                        "windchill_c": 24.5,
                        "windchill_f": 76.1,
                        "heatindex_c": 26.3,
                        "heatindex_f": 79.3,
                        "dewpoint_c": 19.6,
                        "dewpoint_f": 67.3,
                        "will_it_rain": 0,
                        "chance_of_rain": "0",
                        "will_it_snow": 0,
                        "chance_of_snow": "0",
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 15.4,
                        "gust_kph": 24.8
                    },
                    {
                        "time_epoch": 1609387200,
                        "time": "2020-12-30 22:00",
                        "temp_c": 23.9,
                        "temp_f": 75.0,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 9.6,
                        "wind_kph": 15.5,
                        "wind_degree": 118,
                        "wind_dir": "ESE",
                        "pressure_mb": 1009.0,
                        "pressure_in": 30.3,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 77,
                        "cloud": 0,
                        "feelslike_c": 25.8,
                        "feelslike_f": 78.4,
                        "windchill_c": 23.9,
                        "windchill_f": 75.0,
                        "heatindex_c": 25.8,
                        "heatindex_f": 78.4,
                        "dewpoint_c": 19.6,
                        "dewpoint_f": 67.3,
                        "will_it_rain": 0,
                        "chance_of_rain": "0",
                        "will_it_snow": 0,
                        "chance_of_snow": "0",
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 16.8,
                        "gust_kph": 27.0
                    },
                    {
                        "time_epoch": 1609390800,
                        "time": "2020-12-30 23:00",
                        "temp_c": 23.5,
                        "temp_f": 74.3,
                        "is_day": 0,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            "code": 1003
                        },
                        "wind_mph": 10.3,
                        "wind_kph": 16.6,
                        "wind_degree": 120,
                        "wind_dir": "ESE",
                        "pressure_mb": 1009.0,
                        "pressure_in": 30.3,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 80,
                        "cloud": 2,
                        "feelslike_c": 25.5,
                        "feelslike_f": 77.9,
                        "windchill_c": 23.5,
                        "windchill_f": 74.3,
                        "heatindex_c": 25.5,
                        "heatindex_f": 77.9,
                        "dewpoint_c": 19.8,
                        "dewpoint_f": 67.6,
                        "will_it_rain": 0,
                        "chance_of_rain": "0",
                        "will_it_snow": 0,
                        "chance_of_snow": "0",
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 17.2,
                        "gust_kph": 27.7
                    }
                ]
            }
        ]
    } ,
    "alert": {
        
    }
}

const astroIndore = 
{
    "location": {
        "name": "Indore",
        "region": "Madhya Pradesh",
        "country": "India",
        "lat": 22.72,
        "lon": 75.83,
        "tz_id": "Asia/Kolkata",
        "localtime_epoch": 1609349345,
        "localtime": "2020-12-30 22:59"
    },
    "astronomy": {
        "astro": {
            "sunrise": "07:07 AM",
            "sunset": "05:52 PM",
            "moonrise": "06:05 PM",
            "moonset": "07:10 AM",
            "moon_phase": "Full Moon",
            "moon_illumination": "100"
        }
    }
}

export {city , astroIndore};